# Generated by Django 5.0.4 on 2024-04-18 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255)),
                ('machine_serial_no', models.CharField(max_length=255, unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_no', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('material_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='api.machine')),
            ],
        ),
    ]
