# Generated by Django 5.0.4 on 2024-04-18 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_time', models.DurationField()),
                ('production_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.productionlog')),
            ],
        ),
    ]
