# Generated by Django 5.0.4 on 2024-04-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.TextField(max_length=200),
        ),
    ]
