# Generated by Django 5.0.4 on 2024-04-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_video_bucket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default='https://www.datapro.in/uploads/c2fcd84408955736c701e1e81ca05577.png', max_length=300),
        ),
    ]
