# Generated by Django 5.0.4 on 2024-04-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='link',
            new_name='url',
        ),
    ]
