# Generated by Django 5.0.4 on 2024-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bucket_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
