# Generated by Django 5.0.4 on 2024-04-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
